[tool.poetry]
name = "micrograd"
version = "0.1.0"
description = ""
authors = ["kamaraj1226 <kamaraj1226@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
